-- ====================================================================
-- SISTEMA LUMINARIA - MUNICIPALIDAD DE NEUQUÉN
-- Script DDL de Base de Datos para Supabase (PostgreSQL Cloud)
-- Modelo Relacional alineado al DER con soporte para UI, Auth y Hardware
-- ====================================================================

-- 1. TABLA: zona
CREATE TABLE IF NOT EXISTS public.zona (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

-- 2. TABLA: tablero
CREATE TABLE IF NOT EXISTS public.tablero (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_zona INTEGER NOT NULL REFERENCES public.zona(id) ON DELETE CASCADE,
  codigo VARCHAR(50) UNIQUE,
  nombre VARCHAR(150),
  ubicacion TEXT,
  pos_x REAL DEFAULT 50,
  pos_y REAL DEFAULT 50,
  fase VARCHAR(10) DEFAULT 'L1',
  tension_nominal NUMERIC(6,2) NOT NULL DEFAULT 220.00,
  tension_medida_v NUMERIC(6,2) NOT NULL DEFAULT 220.00,
  estado VARCHAR(20) NOT NULL DEFAULT 'ok',
  focos JSONB NOT NULL DEFAULT '{}'::jsonb,
  ultima_modificacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. TABLA: sensor
CREATE TABLE IF NOT EXISTS public.sensor (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tablero INTEGER NOT NULL REFERENCES public.tablero(id) ON DELETE CASCADE,
  mac VARCHAR(50) NOT NULL UNIQUE,
  ultima_modificacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. TABLA: lectura
CREATE TABLE IF NOT EXISTS public.lectura (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sensor INTEGER NOT NULL REFERENCES public.sensor(id) ON DELETE CASCADE,
  id_tablero INTEGER NOT NULL REFERENCES public.tablero(id) ON DELETE CASCADE,
  amperaje NUMERIC NOT NULL,
  tension_v NUMERIC(6,2) DEFAULT 220.00,
  fase VARCHAR(10) DEFAULT 'L1',
  fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. TABLA: tecnico
CREATE TABLE IF NOT EXISTS public.tecnico (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  dni VARCHAR(15) NOT NULL UNIQUE,
  telefono VARCHAR(20),
  email VARCHAR(100) UNIQUE,
  usuario VARCHAR(50) NOT NULL UNIQUE,
  contrasenia VARCHAR(255) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 6. TABLA: admin
CREATE TABLE IF NOT EXISTS public.admin (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  usuario VARCHAR(50) NOT NULL UNIQUE,
  contrasenia VARCHAR(255) NOT NULL,
  dni VARCHAR(15) NOT NULL UNIQUE,
  telefono VARCHAR(20),
  email VARCHAR(100) UNIQUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. TABLA: alerta
CREATE TABLE IF NOT EXISTS public.alerta (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_lectura INTEGER REFERENCES public.lectura(id) ON DELETE SET NULL,
  id_tablero INTEGER NOT NULL REFERENCES public.tablero(id) ON DELETE CASCADE,
  id_tecnico INTEGER REFERENCES public.tecnico(id) ON DELETE SET NULL,
  tipo VARCHAR(50) NOT NULL,
  prioridad VARCHAR(20) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(),
  titulo VARCHAR(255),
  ubicacion TEXT,
  datos_json JSONB DEFAULT '{}'::jsonb,
  tecnico_resolucion VARCHAR(150),
  fecha_resolucion TIMESTAMPTZ
);

-- 8. TABLA: gestiona (Relación N:M entre admin y tecnico según DER)
CREATE TABLE IF NOT EXISTS public.gestiona (
  id_admin INTEGER NOT NULL REFERENCES public.admin(id) ON DELETE CASCADE,
  id_tecnico INTEGER NOT NULL REFERENCES public.tecnico(id) ON DELETE CASCADE,
  fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id_admin, id_tecnico)
);

-- Vista/Sinónimo admin_tecnico para compatibilidad
CREATE OR REPLACE VIEW public.admin_tecnico WITH (security_invoker = true) AS
SELECT id_admin, id_tecnico, fecha_asignacion FROM public.gestiona;

-- 9. AUDIT_LOG
CREATE TABLE IF NOT EXISTS public.audit_log (
  id_audit BIGSERIAL PRIMARY KEY,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
  id_usuario INTEGER,
  accion TEXT NOT NULL,
  recurso TEXT NOT NULL,
  id_recurso TEXT,
  ip_origen TEXT,
  detalles JSONB,
  correlation_id TEXT
);

-- ====================================================================
-- ÍNDICES DE RENDIMIENTO (INCLUYENDO CUBRIENTES DE FK)
-- ====================================================================
CREATE INDEX IF NOT EXISTS idx_tablero_zona ON public.tablero(id_zona);
CREATE INDEX IF NOT EXISTS idx_sensor_tablero ON public.sensor(id_tablero);
CREATE INDEX IF NOT EXISTS idx_lectura_tablero_fecha ON public.lectura(id_tablero, fecha_hora DESC);
CREATE INDEX IF NOT EXISTS idx_alerta_tablero_fecha ON public.alerta(id_tablero, fecha_hora DESC);
CREATE INDEX IF NOT EXISTS idx_alerta_estado ON public.alerta(estado);
CREATE INDEX IF NOT EXISTS idx_tecnico_usuario ON public.tecnico(usuario);
CREATE INDEX IF NOT EXISTS idx_tecnico_email ON public.tecnico(email);
CREATE INDEX IF NOT EXISTS idx_admin_usuario ON public.admin(usuario);
CREATE INDEX IF NOT EXISTS idx_admin_email ON public.admin(email);

CREATE INDEX IF NOT EXISTS idx_fk_alerta_lectura ON public.alerta(id_lectura);
CREATE INDEX IF NOT EXISTS idx_fk_alerta_tablero ON public.alerta(id_tablero);
CREATE INDEX IF NOT EXISTS idx_fk_alerta_tecnico ON public.alerta(id_tecnico);
CREATE INDEX IF NOT EXISTS idx_fk_gestiona_tecnico ON public.gestiona(id_tecnico);
CREATE INDEX IF NOT EXISTS idx_fk_lectura_sensor ON public.lectura(id_sensor);
CREATE INDEX IF NOT EXISTS idx_fk_lectura_tablero ON public.lectura(id_tablero);
CREATE INDEX IF NOT EXISTS idx_fk_sensor_tablero ON public.sensor(id_tablero);
CREATE INDEX IF NOT EXISTS idx_fk_tablero_zona ON public.tablero(id_zona);

-- ====================================================================
-- VISTAS DE COMPATIBILIDAD PLURAL PARA LA UI Y CONSUMO REST (SECURITY INVOKER)
-- ====================================================================
CREATE OR REPLACE VIEW public.tableros WITH (security_invoker = true) AS 
SELECT 
  id,
  coalesce(codigo, 'TABLERO_' || lpad(id::text, 2, '0')) AS id_tablero,
  nombre AS nombre_tablero,
  ubicacion,
  pos_x,
  pos_y,
  fase,
  tension_nominal,
  tension_medida_v,
  estado,
  focos,
  ultima_modificacion AS ultima_actualizacion
FROM public.tablero;

CREATE OR REPLACE VIEW public.alertas WITH (security_invoker = true) AS
SELECT
  id AS id_alerta,
  coalesce((SELECT codigo FROM public.tablero WHERE tablero.id = alerta.id_tablero), 'TABLERO_' || lpad(id_tablero::text, 2, '0')) AS id_tablero,
  id_tablero AS id_tablero_num,
  tipo AS tipo_evento,
  prioridad,
  titulo,
  ubicacion,
  datos_json,
  estado AS estado_alerta,
  fecha_hora AS fecha_hora_generada,
  fecha_resolucion,
  tecnico_resolucion
FROM public.alerta;

-- Vista unificada de usuarios para autenticación
CREATE OR REPLACE VIEW public.usuarios WITH (security_invoker = true) AS
SELECT 
  id AS id_usuario,
  id,
  nombre,
  apellido,
  dni,
  telefono,
  usuario,
  email,
  contrasenia AS password_hash,
  'admin'::text AS rol,
  activo,
  created_at
FROM public.admin
UNION ALL
SELECT 
  id AS id_usuario,
  id,
  nom AS nombre,
  apellido,
  dni,
  telefono,
  usuario,
  email,
  contrasenia AS password_hash,
  'tecnico'::text AS rol,
  activo,
  created_at
FROM public.tecnico;

-- Triggers INSTEAD OF para permitir INSERT / UPDATE sobre las vistas
CREATE OR REPLACE FUNCTION public.trg_alertas_view_insert()
RETURNS TRIGGER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_id_tablero integer;
BEGIN
  IF NEW.id_tablero ~ '^[0-9]+$' THEN
    v_id_tablero := NEW.id_tablero::integer;
  ELSE
    SELECT id INTO v_id_tablero FROM public.tablero WHERE codigo = NEW.id_tablero LIMIT 1;
    IF v_id_tablero IS NULL THEN
      SELECT id INTO v_id_tablero FROM public.tablero WHERE id = NULLIF(regexp_replace(NEW.id_tablero, '[^0-9]', '', 'g'), '')::integer LIMIT 1;
    END IF;
  END IF;
  
  IF v_id_tablero IS NULL THEN
    v_id_tablero := 1;
  END IF;

  INSERT INTO public.alerta (
    id_tablero, tipo, prioridad, estado, fecha_hora, titulo, ubicacion, datos_json, tecnico_resolucion, fecha_resolucion
  ) VALUES (
    v_id_tablero,
    COALESCE(NEW.tipo_evento, 'ALERTA'),
    COALESCE(NEW.prioridad, 'INFO'),
    COALESCE(NEW.estado_alerta, 'pendiente'),
    COALESCE(NEW.fecha_hora_generada, now()),
    NEW.titulo,
    NEW.ubicacion,
    COALESCE(NEW.datos_json, '{}'::jsonb),
    NEW.tecnico_resolucion,
    NEW.fecha_resolucion
  ) RETURNING id INTO NEW.id_alerta;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_alertas_insert ON public.alertas;
CREATE TRIGGER trg_alertas_insert
INSTEAD OF INSERT ON public.alertas
FOR EACH ROW EXECUTE FUNCTION public.trg_alertas_view_insert();

CREATE OR REPLACE FUNCTION public.trg_alertas_view_update()
RETURNS TRIGGER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE public.alerta
  SET 
    estado = COALESCE(NEW.estado_alerta, estado),
    fecha_resolucion = COALESCE(NEW.fecha_resolucion, fecha_resolucion),
    tecnico_resolucion = COALESCE(NEW.tecnico_resolucion, tecnico_resolucion)
  WHERE id = NEW.id_alerta;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_alertas_update ON public.alertas;
CREATE TRIGGER trg_alertas_update
INSTEAD OF UPDATE ON public.alertas
FOR EACH ROW EXECUTE FUNCTION public.trg_alertas_view_update();

CREATE OR REPLACE FUNCTION public.trg_tableros_view_update()
RETURNS TRIGGER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE public.tablero
  SET
    tension_medida_v = COALESCE(NEW.tension_medida_v, tension_medida_v),
    estado = COALESCE(NEW.estado, estado),
    focos = COALESCE(NEW.focos, focos),
    ultima_modificacion = now()
  WHERE codigo = NEW.id_tablero OR id::text = NEW.id_tablero;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tableros_update ON public.tableros;
CREATE TRIGGER trg_tableros_update
INSTEAD OF UPDATE ON public.tableros
FOR EACH ROW EXECUTE FUNCTION public.trg_tableros_view_update();

-- ====================================================================
-- ROW LEVEL SECURITY (RLS)
-- ====================================================================
ALTER TABLE public.zona ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tablero ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lectura ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tecnico ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gestiona ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura publica zona" ON public.zona;
CREATE POLICY "Lectura publica zona" ON public.zona FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Lectura publica tablero" ON public.tablero;
CREATE POLICY "Lectura publica tablero" ON public.tablero FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Actualizacion publica tablero" ON public.tablero;
CREATE POLICY "Actualizacion publica tablero" ON public.tablero FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Insercion publica tablero" ON public.tablero;
CREATE POLICY "Insercion publica tablero" ON public.tablero FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Lectura publica sensor" ON public.sensor;
CREATE POLICY "Lectura publica sensor" ON public.sensor FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Insercion publica sensor" ON public.sensor;
CREATE POLICY "Insercion publica sensor" ON public.sensor FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Actualizacion publica sensor" ON public.sensor;
CREATE POLICY "Actualizacion publica sensor" ON public.sensor FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Lectura publica lectura" ON public.lectura;
CREATE POLICY "Lectura publica lectura" ON public.lectura FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Insercion publica lectura" ON public.lectura;
CREATE POLICY "Insercion publica lectura" ON public.lectura FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Lectura publica alerta" ON public.alerta;
CREATE POLICY "Lectura publica alerta" ON public.alerta FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Insercion publica alerta" ON public.alerta;
CREATE POLICY "Insercion publica alerta" ON public.alerta FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Actualizacion publica alerta" ON public.alerta;
CREATE POLICY "Actualizacion publica alerta" ON public.alerta FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Lectura publica tecnico" ON public.tecnico;
CREATE POLICY "Lectura publica tecnico" ON public.tecnico FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Insercion publica tecnico" ON public.tecnico;
CREATE POLICY "Insercion publica tecnico" ON public.tecnico FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Lectura publica admin" ON public.admin;
CREATE POLICY "Lectura publica admin" ON public.admin FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Lectura publica gestiona" ON public.gestiona;
CREATE POLICY "Lectura publica gestiona" ON public.gestiona FOR SELECT TO anon, authenticated USING (true);

GRANT ALL ON public.tableros TO anon, authenticated;
GRANT ALL ON public.alertas TO anon, authenticated;
GRANT ALL ON public.usuarios TO anon, authenticated;

-- ====================================================================
-- SUPABASE REALTIME
-- ====================================================================
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tablero;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.alerta;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.lectura;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;
END $$;

-- ====================================================================
-- SEMILLAS INICIALES (Plazas y Parques de Neuquén Capital)
-- ====================================================================
INSERT INTO public.zona (id, nombre)
VALUES (1, 'Neuquén Capital - Sector Centro y Plazas')
ON CONFLICT (id) DO UPDATE SET nombre = EXCLUDED.nombre;

INSERT INTO public.tablero (
  id, id_zona, codigo, nombre, ubicacion, pos_x, pos_y, fase, tension_nominal, tension_medida_v, estado, focos
) VALUES 
(
  1, 1, 'TABLERO_01', 'Parque Central', 'Parque Central - Avenida Olascoaga', 
  26.7, 46.8, 'L1', 220.00, 220.00, 'ok',
  '{"FOCO_A1":{"id":"FOCO_A1","corriente_ma":450,"estado":"ok"},"FOCO_A2":{"id":"FOCO_A2","corriente_ma":450,"estado":"ok"},"FOCO_A3":{"id":"FOCO_A3","corriente_ma":450,"estado":"ok"},"FOCO_A4":{"id":"FOCO_A4","corriente_ma":450,"estado":"ok"}}'::jsonb
),
(
  2, 1, 'TABLERO_02', 'Parque Jaime de Nevares', 'Parque Jaime de Nevares - ex U9', 
  41.2, 56.6, 'L2', 220.00, 220.00, 'ok',
  '{"FOCO_B1":{"id":"FOCO_B1","corriente_ma":450,"estado":"ok"},"FOCO_B2":{"id":"FOCO_B2","corriente_ma":450,"estado":"ok"},"FOCO_B3":{"id":"FOCO_B3","corriente_ma":450,"estado":"ok"}}'::jsonb
),
(
  3, 1, 'TABLERO_03', 'Plaza de las Banderas', 'Plaza de las Banderas - Avenida Argentina', 
  26.2, 84.5, 'L3', 220.00, 220.00, 'ok',
  '{"FOCO_C1":{"id":"FOCO_C1","corriente_ma":450,"estado":"ok"},"FOCO_C2":{"id":"FOCO_C2","corriente_ma":450,"estado":"ok"}}'::jsonb
),
(
  4, 1, 'TABLERO_04', 'Paseo de la Costa', 'Paseo de la Costa - Río Limay', 
  36.2, 8.7, 'L1', 220.00, 220.00, 'ok',
  '{"FOCO_D1":{"id":"FOCO_D1","corriente_ma":450,"estado":"ok"},"FOCO_D2":{"id":"FOCO_D2","corriente_ma":450,"estado":"ok"}}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  codigo = EXCLUDED.codigo,
  nombre = EXCLUDED.nombre,
  ubicacion = EXCLUDED.ubicacion,
  pos_x = EXCLUDED.pos_x,
  pos_y = EXCLUDED.pos_y,
  fase = EXCLUDED.fase,
  tension_nominal = EXCLUDED.tension_nominal,
  estado = EXCLUDED.estado;
